
PYTHON = "python"
JS = "js"
JAVA = "java"
CPP = "c++"
PHP = "php"
GO = "go"

EU = "European Union"
USA = "United States"
UA = "Ukraine"
UK = "United Kingdom"

CLUSTERS = {
    PYTHON: {
     "name": "Python",
     "technologies": (
                        "Django",
                        "Flask",
                        "FastAPI",
                        "Tornado",
                        "Pyramid",
                        "Bottle",
                        "SQLAlchemy",
                        "Celery",
                        "PyTest",
                        "NumPy",
                        "Pandas",
                        "PyTorch",
                        "Pydantic",
                        "TensorFlow",
                        "Scikit-learn",
                        "Keras",
                        "Matplotlib",
                        "Plotly",
                        "Pydantic",
                        "PySpark",
                        "Jupyter",
                        "Gunicorn",
                        "uWSGI",
                        "Twisted",
                        "Scrapy",
                        "PyQt",
                        "Tkinter",
                        "Pipenv",
                        "Virtualenv",
                        "Ansible",
                        "SaltStack"
                    ),
    "keywords": {"ln_kw": "python",
                 "dj_kw": "Python"}},
    JAVA : {
     "name": "Java",
     "technologies": (
                        "Spring",
                        "Hibernate",
                        "Maven",
                        "Gradle",
                        "JUnit",
                        "Apache Tomcat",
                        "JSF (JavaServer Faces)",
                        "JSP (JavaServer Pages)",
                        "EJB (Enterprise JavaBeans)",
                        "JDBC (Java Database Connectivity)",
                        "Struts",
                        "GWT (Google Web Toolkit)",
                        "Play Framework",
                        "Vaadin",
                        "JavaFX",
                        "Kotlin",
                        "Groovy",
                        "Log4j",
                        "Jersey (JAX-RS)",
                        "Thymeleaf",
                        "Micronaut",
                        "Quarkus",
                        "Apache Ant",
                        "NetBeans",
                        "Eclipse"
                    ),
    "keywords": {"ln_kw": "java",
                 "dj_kw": "Java"}},
    JS: {
     "name": "Java Script",
     "technologies": (  
                        "React",
                        "Vue",
                        "Angular",
                        "Node.js",
                        "Express",
                        "Next.js",
                        "Nuxt.js",
                        "Svelte",
                        "Ember.js",
                        "Backbone.js",
                        "jQuery",
                        "Meteor",
                        "Gatsby",
                        "NestJS",
                        "Electron",
                        "Redux",
                        "RxJS",
                        "Jest",
                        "Mocha",
                        "Chai",
                        "Webpack",
                        "Grunt",
                        "Gulp",
                        "Babel",
                        "TypeScript",
                        "Nginx",
                        "HTML",
                        "CSS",
                    ),
    "keywords": {"ln_kw": "java script",
                 "dj_kw": "JavaScript"}},
    CPP: {
     "name": "C++",
     "technologies": (
                        "Qt",
                        "Boost",
                        "CMake",
                        "Catch2",
                        "Google Test (gTest)",
                        "wxWidgets",
                        "SFML",
                        "SDL",
                        "OpenGL",
                        "Vulkan",
                        "Poco",
                        "TBB (Threading Building Blocks)",
                        "LLVM",
                        "ACE",
                        "CopperSpice",
                        "JUCE",
                        "FLTK",
                        "Boost.Test",
                        "CPPUnit",
                        "GCC",
                        "Clang",
                        "MSVC",
                        "Make",
                        "Premake"
                    ),
    "keywords": {"ln_kw": "c++",
                 "dj_kw": "CPP"}},              
    PHP: {
     "name": "PHP",
     "technologies": (
                        "Laravel",
                        "Symfony",
                        "CodeIgniter",
                        "Zend Framework",
                        "Phalcon",
                        "Slim",
                        "CakePHP",
                        "Yii",
                        "FuelPHP",
                        "Lumen",
                        "Wordpress"
                    ),
    "keywords": {"ln_kw": "php",
                 "dj_kw": "PHP"}},              
    GO: {
     "name": "Golang",
     "technologies": (
                        "Gin",
                        "Echo",
                        "Fiber",
                        "Beego",
                        "Revel",
                        "Chi",
                        "Buffalo",
                        "Iris",
                        "Martini",
                        "Gorilla",
                    ),
    "keywords": {"ln_kw": "golang",
                 "dj_kw": "Golang"}},              
}

OTHER_TECHS = ["Git", 
               "Linux", 
               "Docker", 
               "Kubernetes", 
               "AWS", 
               "ElasticSearch", 
               "MongoDB", 
               "Postgress",
               "REST",
               "SCRUM",
               "AGILE",
               "SQL",
               "SOAP",
               "MySQL",
               "AI",
               "Machine Learning",
               "Azure"
               ]

NOT_DEFINED = "This requirement wasn't defined in vacancy."