DELAY_3_6 = (3, 6)
DELAY_4_8 = (4, 8) 
DELAY_5_10 = (5, 10)
DELAY_8_10 = (8, 10)
DELAY_10_15 = (10, 15)

PYTHON = "python"
JS = "js"
JAVA = "java"
CPP = "c++"

NOT_DEFINED = "This requirement wasn't defined in vacancy."

OTHER_TECHS = ["Git", 
               "Linux", 
               "Docker", 
               "Kubernetes", 
               "AWS", 
               "ElasticSearch", 
               "MongoDB", 
               "Postgress",
               "REST",
               "SCRUM",
               "AGILE",
               "SQL",
               "SOAP",
               "MySQL",
               "AI",
               "Machine Learning"
               ]

CLUSTERS = {
    PYTHON: {"name": "Python",
     "technologies": (
                        "Django",
                        "Flask",
                        "FastAPI",
                        "Tornado",
                        "Pyramid",
                        "Bottle",
                        "SQLAlchemy",
                        "Celery",
                        "PyTest",
                        "NumPy",
                        "Pandas",
                        "PyTorch",
                        "Pydantic",
                        "TensorFlow",
                        "Scikit-learn",
                        "Keras",
                        "Matplotlib",
                        "Plotly",
                        "Pydantic",
                        "PySpark",
                        "Jupyter",
                        "Gunicorn",
                        "uWSGI",
                        "Twisted",
                        "Scrapy",
                        "PyQt",
                        "Tkinter",
                        "Pipenv",
                        "Virtualenv",
                        "Ansible",
                        "SaltStack"
                    ),
    "keywords": {"ln_kw": "python",
                 "dj_kw": "Python"}},
    JAVA : {"name": "Java",
     "technologies": (
                        "Spring",
                        "Hibernate",
                        "Apache Maven",
                        "Gradle",
                        "JUnit",
                        "Apache Tomcat",
                        "JSF (JavaServer Faces)",
                        "JSP (JavaServer Pages)",
                        "EJB (Enterprise JavaBeans)",
                        "JDBC (Java Database Connectivity)",
                        "Struts",
                        "GWT (Google Web Toolkit)",
                        "Play Framework",
                        "Vaadin",
                        "JavaFX",
                        "Kotlin",
                        "Groovy",
                        "Log4j",
                        "Jersey (JAX-RS)",
                        "Thymeleaf",
                        "Micronaut",
                        "Quarkus",
                        "Apache Ant",
                        "NetBeans",
                        "Eclipse"
                    ),
    "keywords": {"ln_kw": "java",
                 "dj_kw": "Java"}},
    JS: {"name": "Java Script",
     "technologies": (  
                        "React",
                        "Vue",
                        "Angular",
                        "Node.js",
                        "Express",
                        "Next.js",
                        "Nuxt.js",
                        "Svelte",
                        "Ember.js",
                        "Backbone.js",
                        "jQuery",
                        "Meteor",
                        "Gatsby",
                        "NestJS",
                        "Electron",
                        "Redux",
                        "RxJS",
                        "Jest",
                        "Mocha",
                        "Chai",
                        "Webpack",
                        "Grunt",
                        "Gulp",
                        "Babel",
                        "TypeScript",
                        "Nginx",
                        "HTML",
                        "CSS",
                    ),
    "keywords": {"ln_kw": "java script",
                 "dj_kw": "JavaScript"}},
    CPP: {"name": "C++",
     "technologies": (
                        "Qt",
                        "Boost",
                        "CMake",
                        "Catch2",
                        "Google Test (gTest)",
                        "wxWidgets",
                        "SFML",
                        "SDL",
                        "OpenGL",
                        "Vulkan",
                        "Poco",
                        "TBB (Threading Building Blocks)",
                        "LLVM",
                        "ACE",
                        "CopperSpice",
                        "JUCE",
                        "FLTK",
                        "Boost.Test",
                        "CPPUnit",
                        "GCC",
                        "Clang",
                        "MSVC",
                        "Make",
                        "Premake"
                    ),
    "keywords": {"ln_kw": "c++",
                 "dj_kw": "CPP"}},
                
}

DJINNI_HEADERS = {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "uk-UA,uk;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6",
    "cache-control": "max-age=0",
    "connection": "keep-alive",
    "content-length": "130",
    "content-type": "application/x-www-form-urlencoded",
    "cookie": "",
    "host": "djinni.co",
    "origin": "https://djinni.co",
    "referer": "https://djinni.co/login?from=frontpage_main",
    "sec-ch-ua": '"Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"',
    "sec-ch-ua-mobile": "?1",
    "sec-ch-ua-platform": '"Android"',
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36"
    }